#pragma kernel SinCos;

#include "BeamImageCommon.hlsl"

BeamTextureUniformDef(uInput);
RWTexture2D<float4> uSinOutput;
RWTexture2D<float4> uCosOutput;

[numthreads(16,16,1)]
void SinCos(uint3 id : SV_DispatchThreadID)
{
    uint2 size;
    uSinOutput.GetDimensions(size.x, size.y);
    float2 uv = (float2(id.xy) + 0.5) / size;
    float4 input = SampleBeamTexture(uInput, uv);
    uSinOutput[id.xy] = sin(input);
    uCosOutput[id.xy] = cos(input);
}
